CREATE TABLE DIM_DATE
(
	"DATE" DATE NOT NULL,
	"YEAR" INT NOT NULL,
	"MONTH" INT NOT NULL,
	"DAY" INT NOT NULL,
	DAY_OF_WEEK INT NOT NULL,
	DAY_OF_YEAR INT NOT NULL
)
WITH (APPENDOPTIMIZED=TRUE, ORIENTATION=COLUMN, COMPRESSTYPE=ZLIB, COMPRESSLEVEL=5)
DISTRIBUTED BY ("DATE")
;