CREATE TABLE FACT_ORDERS
(
	ORDER_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	CLIENT_ID INT NOT NULL,
	ORDER_DATE DATE NOT NULL,
	QUANTITY INT NOT NULL
)
WITH (APPENDOPTIMIZED=TRUE, ORIENTATION=COLUMN, COMPRESSTYPE=ZLIB, COMPRESSLEVEL=1)
DISTRIBUTED BY (PRODUCT_ID, CLIENT_ID)
;